### PR TITLE
Optimizations and Bugfixes

### PR DESCRIPTION
**Pull request by dnlmlr**
- Changed the hidlib backend on linux from libusb-1.0 to hidraw, to fix an upload bug on linux.
- Changed the help function (--help) to be more helpful.
- Made some minor optimizations to readability and the code itself.

### CODE REVIEW

**Comment by a3f** [comment]
You can `git push --force` to your feature branch and Github will update the existing pull request, by the way. I will try to look through the patch this weekend. Thanks. :)

**Comment by dnlmlr** [comment]
Sorry I had to redo this pull request, but I needed to change some wrong metadata in my commits. The actual commits are the same.

**Comment by dnlmlr** [comment]
Yea I know about `git push --force`, but for some reason it did not work in this case. It did do the push, but for some reason the metadata did not change when cloning/pulling it again.

**Comment by a3f** [comment]
Thanks. I rewrote some of the commits; The stray `s` after the `#include` would've broken `git bisect`, so I amended that commit. Same goes for the removed and re-added `EV3-API` submodule. The rest are some minor stylistic issues.

I don't format my code like I did three years ago, so thanks for fixing that too. :)

**Pull request closed without merging**
